<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>axios请求重试</title>
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
</head>
<body>
    <div>
        <h3>请求重试示例</h3>
        <button onclick="handleWithoutRetry()">请求失败不重试</button>
        <button onclick="handleWithRetry()">请求失败重试</button>
    </div>
    <script>
        // 请求重试
        axios.interceptors.request.use(null, (error) => {
            console.log('请求失败', error);
            let config = error.config; // 获取请求配置信息
            if (!config || !config.retry) return Promise.reject(error); // 如果请求配置不存在或者不需要重试，则直接返回错误信息
            const { _retryCount = 0, retryDelay = 300, retryTimes = 3 } = config; // 获取请求配置信息中的重试信息
            // 在请求配置信息中添加重试次数
            config._retryCount = _retryCount;
            // 如果重试次数超过了最大重试次数，则直接返回错误信息
            if (_retryCount >= retryTimes) return Promise.reject(error);
            // 计算下一次重试的时间
            const waitTime = retryDelay * Math.pow(2, _retryCount);
            // 设置请求配置信息的重试次数
            config._retryCount += 1;
            // 返回一个延迟的 Promise 对象
            return new Promise((resolve) => setTimeout(() => resolve(axios(config)), waitTime));
        });

        // 请求失败不重试
        function handleWithoutRetry() {
            axios.post('https://apifoxmock.com/m2/5552656-5229673-default/250704284').then((res) => {
                console.log('请求成功', res);
            }).catch((error) => {
                console.log('请求失败', error);
            });
        }

        // 请求失败重试
        function handleWithRetry() {
            axios.post('https://apifoxmock.com/m2/5552656-5229673-default/250704284', {
                retryTimes: 3
            }).then((res) => {
                console.log('请求成功', res);
            }).catch((error) => {
                console.log('请求失败', error);
            });
        }
    </script>
</body>
</html>